# ruff: noqa: E501
"""Build the reviewed Milestone 4C corpus and its pinned licensed media.

This authoring tool contains only public source metadata. It never reads application
configuration or databases. Re-running it is deterministic except for a deliberate
failure when an upstream media file changes bytes.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import time
import urllib.parse
from pathlib import Path

from backend.app.domains.discovery.corpus import CuratedDiscovery

ROOT = Path(__file__).resolve().parents[1]
MEDIA_DIR = ROOT / "frontend" / "public" / "media" / "discoveries"
CORPUS_PATH = (
    ROOT / "backend" / "app" / "domains" / "discovery" / "curated_new_plant_corpus.json"
)

RECORDS = [
    {
        "key": "moringa",
        "common": "Moringa",
        "scientific": "Moringa oleifera Lam.",
        "family": "Moringaceae",
        "powo": "584736-1",
        "range": "Native from northeastern Pakistan to northwestern India",
        "codes": ["PK", "IN"],
        "pmid": "41305552",
        "doi": "10.3390/nu17223501",
        "date": "2025-11-07",
        "title": "Effects of Moringa oleifera Lam. Supplementation on Cardiometabolic Outcomes: A Meta-Analysis of Randomized Controlled Trials with GRADE Assessment.",
        "authors": [
            "Diana Crișan",
            "Laura Gavrilaș",
            "Ramona Păltinean",
            "Oleg Frumuzachi",
            "Andrei Mocan",
            "Gianina Crișan",
        ],
        "journal": "Nutrients",
        "types": ["Journal Article", "Meta-Analysis", "Systematic Review"],
        "headline": "Moringa meta-analysis finds no consistent cardiometabolic benefit",
        "standfirst": "Nine randomized trials did not support consistent cardiometabolic benefits from moringa supplementation; one blood-pressure signal weakened during sensitivity analysis and every assessed outcome received very-low-certainty evidence.",
        "question": "Across randomized adult trials, does moringa supplementation change body measurements, blood lipids, glucose measures, or blood pressure?",
        "context": "Moringa leaves and other plant parts are foods and components of traditional practices in parts of Africa and Asia. The review tested modern supplement claims against controlled evidence rather than treating those histories as proof of efficacy.",
        "methods": "The authors searched three databases through 7 April 2025, included adult randomized trials lasting at least two weeks, pooled outcomes with random-effects models, assessed bias with RoB 2, and rated certainty with GRADE.",
        "base": "Nine trials contributed 12 study arms: 341 participants received moringa and 308 were in control groups. Products, doses, durations, populations, and cardiometabolic endpoints varied.",
        "intervention": "Moringa preparations used in the included trials.",
        "comparator": "Placebo or control conditions used by each randomized trial.",
        "findings": [
            "Most measured cardiometabolic outcomes did not differ significantly.",
            "Diastolic blood pressure showed a modest pooled reduction, but it was not robust in sensitivity analysis.",
            "GRADE certainty was very low for every evaluated outcome.",
        ],
        "strength": "low",
        "strength_text": "Randomization and formal GRADE assessment strengthen the review process, but small trials, bias, indirectness, and frequently high heterogeneity make the estimated effects very uncertain.",
        "matters": "A careful negative result helps distinguish biological plausibility and traditional use from demonstrated clinical benefit. It also directs future work toward larger, standardized trials.",
        "limits": [
            "Trials were small and methodologically uneven.",
            "Products and outcome definitions differed.",
            "Several pooled outcomes had heterogeneity above 80 percent.",
            "The isolated blood-pressure signal did not survive sensitivity testing.",
        ],
        "safety": "The indexed review focused on cardiometabolic efficacy and does not establish broad safety across plant parts, preparations, medicines, pregnancy, or long-term use. Product identity and contamination remain separate questions.",
        "unknown": [
            "The review does not prove that moringa prevents or treats diabetes or cardiovascular disease.",
            "It does not establish an effective preparation or dose.",
            "Subgroup observations cannot substitute for prospectively designed trials.",
        ],
        "practical": "The strongest reading is restraint: current randomized evidence is too uncertain to support broad cardiometabolic promises for moringa supplements.",
        "traditional": "Kew records Moringa oleifera as a plant used for food and medicine. That documented use context explains research interest but is not clinical-effect evidence.",
        "preparation": "Included trials tested various moringa supplements rather than one standardized product. The meta-analysis therefore cannot make every leaf powder, extract, or food preparation interchangeable.",
        "outcomes": "The review examined anthropometric measures, lipid profiles, glycemic indices, and blood pressure. Reporting outcome-by-outcome matters because a weak signal in one measure does not imply general metabolic benefit.",
        "related": "The review's subgroup findings were exploratory and should be treated as hypotheses. Larger trials need verified plant material, defined preparations, adequate duration, and preregistered outcomes.",
        "research_geo": None,
        "image": (
            58536866,
            "Kalamunggay (Moringa oleifera), Philippines.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Kalamunggay_%28Moringa_oleifera%29%2C_Philippines.jpg/1280px-Kalamunggay_%28Moringa_oleifera%29%2C_Philippines.jpg",
            "Obsidian Soul",
            "CC0 1.0",
            "https://creativecommons.org/publicdomain/zero/1.0/",
            "Documentary image of moringa leaves; not from the reported study.",
        ),
    },
    {
        "key": "holy-basil",
        "common": "Holy basil",
        "scientific": "Ocimum tenuiflorum L.",
        "family": "Lamiaceae",
        "powo": "453130-1",
        "range": "Native across tropical and subtropical Asia to the western Pacific",
        "codes": [
            "IN",
            "BD",
            "LK",
            "TH",
            "VN",
            "PH",
            "AU",
            "CN",
            "ID",
            "NP",
            "PK",
            "MM",
            "KH",
            "LA",
            "PG",
        ],
        "pmid": "37829808",
        "doi": "10.1016/j.heliyon.2023.e20691",
        "date": "2023-10-05",
        "title": "Benefits of basil tea for patients with differentiated thyroid cancer during radioiodine therapy: A randomized controlled trial.",
        "authors": ["Kenta Nomura", "Michihiro Nakayama", "Atsutaka Okizaki"],
        "journal": "Heliyon",
        "types": ["Journal Article"],
        "headline": "Small trial tests holy basil tea during radioiodine therapy",
        "standfirst": "A 44-person randomized study reported differences in anxiety scores, oral measurements, and salivary-gland imaging during radioiodine therapy, but its short duration and small sample keep the findings preliminary.",
        "question": "Could a defined holy basil leaf tea influence anxiety and selected oral or salivary measures during four days of radioiodine therapy?",
        "context": "Holy basil has religious, food, and traditional-use importance in South Asia. Here it was studied as supportive care during a specific cancer-treatment setting, not as a cancer treatment.",
        "methods": "After thyroid removal, 44 people with differentiated thyroid cancer were randomized to holy basil tea or distilled water during radioiodine therapy. Anxiety questionnaires, saliva measures, and scintigraphy were compared.",
        "base": "Twenty-two participants were allocated to each group. The intervention began on the day of therapy and continued after meals for four days, producing a short, tightly bounded observation window.",
        "intervention": "Tea prepared from 2.0 g of Ocimum tenuiflorum leaves in 180 mL, taken after meals for four days.",
        "comparator": "The same volume of distilled water on the same schedule.",
        "findings": [
            "Changes in state and trait anxiety scores favored the tea group.",
            "Several oral test measures changed differently between groups.",
            "A salivary-gland scintigraphy washout measure also differed.",
        ],
        "strength": "limited",
        "strength_text": "Random allocation and an active comparison schedule are useful, but 44 participants, four days of follow-up, multiple outcomes, and unclear masking limit confidence and generalizability.",
        "matters": "The study treats supportive-care outcomes as measurable questions. It should prompt replication, not turn a small tea study into a claim about treating cancer or preventing all therapy complications.",
        "limits": [
            "Only 44 patients participated.",
            "Follow-up lasted four days.",
            "Multiple psychological, microbiological, and imaging endpoints were tested.",
            "The abstract does not report detailed adverse-event or masking procedures.",
        ],
        "safety": "The indexed abstract does not provide a comprehensive safety analysis. People receiving cancer treatment may have medication, hydration, and dietary instructions that should not be displaced by an herbal tea report.",
        "unknown": [
            "The study does not show that holy basil treats thyroid cancer.",
            "It does not establish prevention of long-term salivary injury.",
            "It cannot determine effects in other cancers, treatments, preparations, or populations.",
        ],
        "practical": "This is an early supportive-care signal from one small treatment setting. The clinically responsible next step is independent replication with prespecified outcomes and fuller safety reporting.",
        "traditional": "Kew describes holy basil as a medicinal, food, social, and religious plant. Those traditions provide context for the tea preparation while remaining distinct from this modern clinical question.",
        "preparation": "The researchers used a leaf infusion with a defined amount and volume. Findings cannot automatically be transferred to essential oil, extracts, capsules, culinary basil, or differently prepared teas.",
        "outcomes": "Measured domains included anxiety, saliva chemistry and microbiology, and salivary-gland scintigraphy. These are surrogate or supportive-care outcomes, not tumor response or survival outcomes.",
        "related": "Future work should clarify masking, adverse events, clinical relevance of the measured changes, and whether effects persist after therapy.",
        "research_geo": (
            "Japan",
            "JP",
            "author_affiliation",
            "Research affiliation",
            "PubMed affiliations identify the research team in Japan; this is not asserted as the participant location.",
        ),
        "image": (
            12175019,
            "Tulsi Tea.JPG",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Tulsi_Tea.JPG/1280px-Tulsi_Tea.JPG",
            "Miansari66",
            "Public domain",
            "https://creativecommons.org/publicdomain/mark/1.0/",
            "Documentary image of holy basil tea; not from the reported study.",
        ),
    },
    {
        "key": "centella",
        "common": "Gotu kola",
        "scientific": "Centella asiatica (L.) Urb.",
        "family": "Apiaceae",
        "powo": "1197718-2",
        "range": "Native across tropical and subtropical Old World regions to eastern Australia and the western Pacific",
        "codes": [
            "KR",
            "IN",
            "LK",
            "CN",
            "AU",
            "ZA",
            "NG",
            "ET",
            "ID",
            "TH",
            "VN",
            "JP",
            "PG",
        ],
        "pmid": "42196964",
        "doi": "10.3390/nu18101505",
        "date": "2026-05-08",
        "title": "A Randomized, Double-Blind, Placebo-Controlled Trial Assessing the Effects of Oral Centella asiatica Extract on Skin Aging-Related Parameters in Middle-Aged Korean Women.",
        "authors": [
            "Nayon Hur",
            "Youngha Seo",
            "Jaewoo Bae",
            "Young Jun Kim",
            "Eun Ji Kim",
            "Yean Jung Choi",
        ],
        "journal": "Nutrients",
        "types": ["Journal Article", "Randomized Controlled Trial"],
        "headline": "Centella trial reports wrinkle changes while other skin effects stay modest",
        "standfirst": "In 112 middle-aged Korean women, 12 weeks of oral Centella asiatica extract changed several imaging-based wrinkle measures, while hydration, elasticity, and brightness effects were small and long-term applicability remains unknown.",
        "question": "Does an oral Centella asiatica extract change measured wrinkle and skin-barrier parameters over 12 weeks compared with placebo?",
        "context": "Centella is widely used in dermatological products and traditional practice, but oral supplementation is a different exposure from topical use. The trial addressed that product-specific evidence gap.",
        "methods": "The randomized, double-blind, placebo-controlled trial used three-dimensional wrinkle imaging and non-invasive measures of hydration, transepidermal water loss, elasticity, brightness, and redness.",
        "base": "A total of 112 middle-aged Korean women were randomized. Efficacy was analyzed in the per-protocol population, which may differ from a full intention-to-treat estimate.",
        "intervention": "A specified oral Centella asiatica extract taken daily for 12 weeks.",
        "comparator": "Placebo for the same 12-week period.",
        "findings": [
            "Several wrinkle depth, volume, and roughness measures improved from baseline and differed from minimal placebo changes.",
            "Transepidermal water loss declined and cheek hydration increased.",
            "Elasticity, hydration, and brightness changes were statistically detected but small in magnitude.",
        ],
        "strength": "limited",
        "strength_text": "Blinding, placebo control, and instrument-based measurements are strengths. One demographic group, 12 weeks, per-protocol analysis, multiple endpoints, and modest non-wrinkle changes limit broader claims.",
        "matters": "The detailed measurements separate visually relevant wrinkle outcomes from smaller changes in other skin properties, helping prevent a single broad anti-aging claim from obscuring the actual result pattern.",
        "limits": [
            "The population was limited to middle-aged Korean women.",
            "Follow-up was 12 weeks.",
            "The efficacy analysis used the per-protocol population.",
            "Multiple related skin endpoints were assessed, and some changes were very small.",
        ],
        "safety": "No serious adverse events were reported and monitored laboratory values stayed within reference ranges during 12 weeks. That does not establish long-term safety or safety in pregnancy, illness, or with medicines.",
        "unknown": [
            "The trial does not prove reversal of biological skin aging.",
            "It does not show durable changes after supplementation stops.",
            "It does not establish that topical products or other extracts behave the same way.",
        ],
        "practical": "The trial supports a short-term, product-specific signal in wrinkle imaging, while its small secondary changes and narrow population argue against sweeping anti-aging claims.",
        "traditional": "Kew records Centella asiatica as a medicinal and food plant with a broad Old World distribution. Traditional context is relevant background, not a substitute for the controlled comparison.",
        "preparation": "This was an oral extract, not a topical cream and not an undefined fresh-plant preparation. Product chemistry and bioavailability determine whether another preparation is comparable.",
        "outcomes": "Researchers used three-dimensional imaging plus barrier, hydration, elasticity, and color instruments. A statistically detectable change is not automatically a large or noticeable clinical effect.",
        "related": "Replication should use intention-to-treat analyses, longer follow-up, diverse populations, prespecified primary outcomes, and transparent product characterization.",
        "research_geo": (
            "South Korea",
            "KR",
            "participant_location",
            "Participant location",
            "The indexed title and abstract identify the participants as Korean women.",
        ),
        "image": (
            70874613,
            "Centella asiatica 6107.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Centella_asiatica_6107.jpg/1280px-Centella_asiatica_6107.jpg",
            "Vengolis",
            "CC BY-SA 4.0",
            "https://creativecommons.org/licenses/by-sa/4.0/",
            "Botanical reference image; not an image from the reported study.",
        ),
    },
    {
        "key": "black-seed",
        "common": "Black seed",
        "scientific": "Nigella sativa L.",
        "family": "Ranunculaceae",
        "powo": "711687-1",
        "range": "Native from southeastern Europe and the Caucasus through western and southwestern Iran",
        "codes": ["BG", "CY", "IR", "IQ", "LB", "RO", "TM", "TR", "GE"],
        "pmid": "38777430",
        "doi": "10.1016/j.clnesp.2024.03.020",
        "date": "2024-03-22",
        "title": "Effects of Nigella sativa supplementation on lipid profiles in adults: An updated systematic review and meta-analysis of randomized controlled trials.",
        "authors": [
            "Mahsa Rounagh",
            "Vali Musazadeh",
            "Ali Hosseininejad-Mohebati",
            "Maryam Falahatzadeh",
            "Zeynab Kavyani",
            "Reza Bijan Rostami",
            "Mahdi Vajdi",
        ],
        "journal": "Clinical Nutrition ESPEN",
        "types": ["Journal Article", "Systematic Review", "Meta-Analysis"],
        "headline": "Black-seed review reports lipid changes but leaves clinical certainty unresolved",
        "standfirst": "A 34-study meta-analysis involving 2,278 adults reported pooled changes in cholesterol and triglyceride measures, while the indexed abstract does not provide enough risk-of-bias, heterogeneity, preparation, or safety detail for a treatment conclusion.",
        "question": "Across randomized adult trials, how does Nigella sativa supplementation affect total cholesterol, LDL, HDL, and triglyceride measurements?",
        "context": "Black seed has food and traditional-use histories across parts of western Asia and neighboring regions. Modern products vary from seeds and oils to extracts, making synthesis useful but also methodologically difficult.",
        "methods": "The reviewers searched major databases through December 2022 and pooled randomized-trial lipid outcomes with random-effects models using standardized mean differences.",
        "base": "Thirty-four studies with 2,278 adult participants were included. The abstract reports the aggregate size but not enough product-by-product or population detail to establish interchangeability.",
        "intervention": "Nigella sativa supplements as defined in the included randomized trials.",
        "comparator": "Control conditions from the included trials.",
        "findings": [
            "Pooled estimates favored Nigella sativa for total cholesterol, triglycerides, and LDL cholesterol.",
            "The pooled HDL estimate moved upward.",
            "The abstract's effect estimates do not by themselves establish clinical outcomes such as fewer cardiovascular events.",
        ],
        "strength": "mixed",
        "strength_text": "The number of trials is substantial, but standardized effects are difficult to translate clinically, and the indexed abstract lacks the bias, heterogeneity, product, duration, and adverse-event detail needed for confident application.",
        "matters": "The synthesis identifies a research signal while showing why biomarker movement should not be presented as proof of disease prevention or a substitute for established lipid management.",
        "limits": [
            "The abstract does not report risk-of-bias results.",
            "Preparations, doses, populations, and durations are not summarized in sufficient detail.",
            "Standardized mean differences obscure the absolute clinical size of change.",
            "Cardiovascular events were not the reported endpoint.",
        ],
        "safety": "The indexed abstract does not provide a pooled adverse-event analysis. Seed, oil, and extract products may differ, and interactions or special-population risks cannot be inferred from lipid results.",
        "unknown": [
            "The review does not prove prevention of heart attack or stroke.",
            "It does not identify one universally effective product.",
            "It does not justify replacing prescribed lipid-lowering treatment.",
        ],
        "practical": "The pooled biomarker signal warrants better standardized trials and clinically interpretable reporting; it is not a treatment recommendation.",
        "traditional": "Kew recognizes Nigella sativa as an accepted species native from southeastern Europe toward Iran. Cultural and culinary use contextualize the research without proving lipid effects.",
        "preparation": "The source groups multiple Nigella sativa supplement forms. Without preparation-specific analyses in the indexed abstract, readers should not assume seeds, oils, and extracts are equivalent.",
        "outcomes": "The measured outcomes were blood lipid markers, not symptoms, quality of life, cardiovascular events, or mortality. That distinction limits the strength of practical conclusions.",
        "related": "Future reviews should foreground absolute units, trial bias, adverse events, verified products, and whether effects differ by baseline lipid status.",
        "research_geo": None,
        "image": (
            63481886,
            "Nigella Sativa seed.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Nigella_Sativa_seed.jpg/1280px-Nigella_Sativa_seed.jpg",
            "Afifa Afrin",
            "CC BY-SA 4.0",
            "https://creativecommons.org/licenses/by-sa/4.0/",
            "Documentary image of black seeds; not from the reported study.",
        ),
    },
    {
        "key": "saffron",
        "common": "Saffron",
        "scientific": "Crocus sativus L.",
        "family": "Iridaceae",
        "powo": "436688-1",
        "range": "A cultigen recorded by Kew as native from Greece and introduced in several saffron-growing regions",
        "codes": ["GR", "IR", "IT", "MA", "PK", "ES", "TR"],
        "pmid": "38796446",
        "doi": "10.1186/s12986-024-00806-y",
        "date": "2024-05-25",
        "title": "Effects of Crocus sativus on glycemic control and cardiometabolic parameters among patients with metabolic syndrome and related disorders: a systematic review and meta-analysis of randomized controlled trials.",
        "authors": [
            "Xiaodan Yan",
            "Shuyuan Zhao",
            "Xue Feng",
            "Xinrui Li",
            "Qian Zhou",
            "Qiu Chen",
        ],
        "journal": "Nutrition & Metabolism",
        "types": ["Journal Article", "Review"],
        "headline": "Saffron meta-analysis signals glycemic changes—and a reporting inconsistency",
        "standfirst": "A synthesis of 13 randomized trials and 840 participants reported changes in HbA1c, fasting glucose, cholesterol, and systolic blood pressure, but an internally inconsistent p-value in the indexed abstract makes cautious full-text verification essential.",
        "question": "Do saffron or crocin preparations change glycemic and cardiometabolic markers in people with metabolic syndrome or related disorders?",
        "context": "Saffron is a cultivated spice with a long medical-use history. Trials of whole saffron and crocin do not necessarily test the same exposure, even when combined in one review.",
        "methods": "The authors searched four databases through 30 December 2023, included randomized trials, assessed heterogeneity, and used random-effects weighted mean differences.",
        "base": "Thirteen randomized trials involving 840 patients with metabolic syndrome or related disorders contributed to the synthesis.",
        "intervention": "Crocus sativus or crocin preparations from the included trials.",
        "comparator": "Placebo or other control conditions in the included trials.",
        "findings": [
            "Pooled estimates favored the intervention for HbA1c and fasting glucose.",
            "Total cholesterol changed in the metabolic-syndrome subgroup.",
            "The systolic-blood-pressure line reports a confidence interval excluding zero alongside p=0.99, an inconsistency requiring source-level checking.",
        ],
        "strength": "mixed",
        "strength_text": "Randomized evidence and a multi-database review are strengths, but mixed preparations, related yet different disorders, and an internally inconsistent indexed statistic prevent a high-confidence interpretation.",
        "matters": "Calling out the inconsistency is part of evidence translation: a plausible pooled result should not be repeated uncritically when its own abstract contains conflicting statistical information.",
        "limits": [
            "Saffron and crocin interventions were combined.",
            "Participants had metabolic syndrome and related but non-identical disorders.",
            "The indexed systolic-pressure statistic is internally inconsistent.",
            "The abstract does not provide a complete adverse-event synthesis.",
        ],
        "safety": "The indexed abstract does not establish comprehensive safety. Concentrated saffron or crocin products are not equivalent to culinary exposure, and special-population or interaction questions require separate evidence.",
        "unknown": [
            "The review does not prove prevention of diabetes or cardiovascular events.",
            "It does not resolve which preparation accounts for pooled findings.",
            "The inconsistent blood-pressure statistic should not be used until checked against the full analysis.",
        ],
        "practical": "The review is a signal for careful follow-up, not a basis for self-treatment. The full paper and future standardized trials must resolve product and reporting uncertainty.",
        "traditional": "Kew treats Crocus sativus as a cultivated taxon originating from Greece and documents its introduced range. Spice history explains interest but does not validate concentrated supplements.",
        "preparation": "The review combines whole-saffron and crocin interventions. Those exposures should remain separately identifiable in future trials and evidence summaries.",
        "outcomes": "HbA1c, fasting glucose, blood pressure, and cholesterol are surrogate cardiometabolic markers. The review did not establish patient-important event reduction.",
        "related": "A useful replication agenda includes registered primary outcomes, consistent units, preparation chemistry, adverse-event reporting, and correction of statistical inconsistencies.",
        "research_geo": None,
        "image": (
            84317051,
            "Récolte de Crocus sativus, Taliouine, Morocco 03.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/R%C3%A9colte_de_Crocus_sativus%2C_Taliouine%2C_Morocco_03.jpg/1280px-R%C3%A9colte_de_Crocus_sativus%2C_Taliouine%2C_Morocco_03.jpg",
            "Francois Rodolphe INGOLD",
            "CC BY 4.0",
            "https://creativecommons.org/licenses/by/4.0/",
            "Documentary image of a saffron harvest; not from the reported study.",
        ),
    },
    {
        "key": "bacopa",
        "common": "Bacopa",
        "scientific": "Bacopa monnieri (L.) Wettst.",
        "family": "Plantaginaceae",
        "powo": "1072674-2",
        "range": "Native across tropical and subtropical regions worldwide, with a few documented introductions",
        "codes": [
            "IN",
            "LK",
            "TH",
            "VN",
            "CN",
            "AU",
            "NG",
            "EG",
            "BR",
            "AR",
            "US",
            "MX",
        ],
        "pmid": "38538390",
        "doi": "10.1016/j.explore.2024.02.008",
        "date": "2024-03-03",
        "title": "Evaluating the effects of Bacopa monnieri on cognitive performance and sleep quality of patients with mild cognitive impairment: A triple-blinded, randomized, placebo-controlled trial.",
        "authors": [
            "Maryam Delfan",
            "Parastou Kordestani-Moghaddam",
            "Mohammad Gholami",
            "Khadije Kazemi",
            "Rasool Mohammadi",
        ],
        "journal": "Explore",
        "types": ["Journal Article", "Randomized Controlled Trial"],
        "headline": "Bacopa trial finds selective cognitive signals but no sleep-quality change",
        "standfirst": "A two-month placebo-controlled trial in 62 people with mild cognitive impairment reported changes in selected attention, verbal-fluency, and overall cognitive scores, while overall sleep quality did not differ.",
        "question": "Can a defined Bacopa monnieri extract change cognitive-test performance or self-reported sleep quality over two months in mild cognitive impairment?",
        "context": "Bacopa has a traditional-use history associated with cognition, but mild cognitive impairment is heterogeneous and short questionnaire-based trials cannot establish prevention of dementia.",
        "methods": "Sixty-two patients were assigned to extract or starch placebo. Montreal Cognitive Assessment and Pittsburgh Sleep Quality Index measures were collected before treatment, after one month, and after two months.",
        "base": "The study included 62 people with mild cognitive impairment divided between two groups. The abstract does not report attrition, allocation details, or a full adverse-event table.",
        "intervention": "A Bacopa monnieri extract tablet for two months.",
        "comparator": "A starch-containing placebo tablet.",
        "findings": [
            "Overall cognition did not differ at the first two time points but did at the final assessment.",
            "Attention differed at months one and two, and verbal fluency at month two.",
            "Overall sleep-quality scores did not differ at any time point.",
        ],
        "strength": "limited",
        "strength_text": "Triple blinding and placebo control are valuable, but the small sample, short follow-up, repeated testing, multiple cognitive domains, and sparse safety detail make the signals exploratory.",
        "matters": "The uneven result pattern matters more than a simple positive label: some test domains changed, others did not, and sleep—the second major outcome—showed no overall effect.",
        "limits": [
            "Only 62 participants were studied for two months.",
            "Several domains and time points were tested.",
            "The abstract does not clarify multiplicity adjustment or attrition.",
            "Questionnaire and screening-score changes do not establish durable functional benefit.",
        ],
        "safety": "The indexed abstract does not provide detailed adverse-event findings. Cognitive vulnerability, other medicines, and product variability make broader safety conclusions inappropriate.",
        "unknown": [
            "The trial does not show that bacopa prevents dementia.",
            "It does not establish durable everyday cognitive improvement.",
            "It does not support a sleep benefit in this population.",
        ],
        "practical": "The study offers selective short-term signals that need larger, preregistered replication with functional outcomes and transparent safety reporting.",
        "traditional": "Kew accepts Bacopa monnieri and records medicinal use across its broad tropical and subtropical range. Traditional reputation motivated the question but did not determine the answer.",
        "preparation": "The study used an oral extract tablet. Composition and standardization details are necessary before comparing it with fresh herb, powders, or other commercial extracts.",
        "outcomes": "Cognition was assessed through a screening instrument and named subdomains; sleep through the Pittsburgh index. The absence of a sleep signal should remain as visible as the selected cognitive results.",
        "related": "Next studies should specify a primary cognitive endpoint, adjust for repeated testing, measure daily function, document adverse events, and follow participants longer.",
        "research_geo": None,
        "image": (
            137031020,
            "Bacopa monnieri Brahmi flower.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Bacopa_monnieri_Brahmi_flower.jpg/1280px-Bacopa_monnieri_Brahmi_flower.jpg",
            "Aseedtolife",
            "CC BY-SA 4.0",
            "https://creativecommons.org/licenses/by-sa/4.0/",
            "Botanical reference image; not an image from the reported study.",
        ),
    },
    {
        "key": "rhodiola",
        "common": "Rhodiola",
        "scientific": "Rhodiola rosea L.",
        "family": "Crassulaceae",
        "powo": "315148-2",
        "range": "Native across subarctic and subalpine parts of the Northern Hemisphere",
        "codes": [
            "CA",
            "US",
            "GL",
            "IS",
            "NO",
            "SE",
            "FI",
            "GB",
            "IE",
            "FR",
            "DE",
            "CH",
            "AT",
            "IT",
            "PL",
            "RO",
            "BG",
            "RU",
            "KZ",
            "MN",
            "CN",
            "JP",
            "KR",
            "UA",
        ],
        "pmid": "37495266",
        "doi": "10.1002/ptr.7950",
        "date": "2023-07-26",
        "title": "Rhodiola rosea supplementation on sports performance: A systematic review of randomized controlled trials.",
        "authors": [
            "Patricia M Sanz-Barrio",
            "Eric E Noreen",
            "Laura Gilsanz-Estebaranz",
            "Jorge Lorenzo-Calvo",
            "María Martínez-Ferrán",
            "Helios Pareja-Galeano",
        ],
        "journal": "Phytotherapy Research",
        "types": ["Systematic Review", "Journal Article"],
        "headline": "Rhodiola sports review finds heterogeneous signals under high bias risk",
        "standfirst": "Thirteen randomized trials involving 263 healthy adults produced mixed signals across endurance, anaerobic performance, perceived exertion, and muscle-damage measures; protocols differed and most studies had unclear or high risk of bias.",
        "question": "Does Rhodiola rosea supplementation influence exercise performance, perceived exertion, or markers associated with muscle damage in healthy adults?",
        "context": "Rhodiola is associated with endurance and fatigue claims, but sports studies vary in exercise protocol, timing, extract composition, and endpoint, which can make a simple pooled narrative misleading.",
        "methods": "Two reviewers searched PubMed, Web of Science, and Cochrane through March 2023 for randomized trials in healthy participants not using other supplements.",
        "base": "Thirteen studies included 263 participants—198 men and 65 women aged 18 to 65. Two tested acute use, five chronic use, and six combined both approaches.",
        "intervention": "Rhodiola rosea supplements under acute, chronic, or combined protocols.",
        "comparator": "Control conditions in the eligible randomized trials.",
        "findings": [
            "Eleven studies reported at least one positive finding and two reported no effect.",
            "Signals varied across endurance, anaerobic performance, perceived exertion, heart rate, lactate, and damage markers.",
            "The review itself identified protocol differences and unclear or high bias risk in most studies.",
        ],
        "strength": "low",
        "strength_text": "Restriction to randomized studies is helpful, but just 263 participants, male predominance, inconsistent protocols, many outcomes, and widespread bias concerns make the evidence unstable.",
        "matters": "Athletic-performance claims often collapse many endpoints into one promise. This review instead shows a fragmented literature where a positive result in one measure may not reproduce in another protocol.",
        "limits": [
            "The review included only 65 women.",
            "Exercise and supplementation protocols varied substantially.",
            "Most studies had unclear or high risk of bias.",
            "Multiple physiological and performance outcomes reduce confidence in isolated positive signals.",
        ],
        "safety": "The indexed abstract does not provide a systematic adverse-event synthesis. Exercise performance data cannot establish safety for people with medical conditions, interacting medicines, or prolonged use.",
        "unknown": [
            "The review does not prove a reliable performance benefit for every athlete.",
            "It does not identify an interchangeable class of rhodiola products.",
            "It does not establish long-term safety or clinical benefit.",
        ],
        "practical": "The literature is better described as hypothesis-generating than performance-confirming; standardized independent trials are still needed.",
        "traditional": "Kew accepts Rhodiola rosea across northern alpine and subarctic regions. Historical use provides cultural context, while the sports-performance claims require their own controlled evidence.",
        "preparation": "The review covered acute and chronic supplementation protocols. Without uniform extract standards and timing, results cannot be transferred to any product labeled rhodiola.",
        "outcomes": "Endpoints ranged from perceived exertion to endurance, anaerobic work, heart rate, lactate, creatine kinase, and C-reactive protein. They answer different questions and should not be merged rhetorically.",
        "related": "Future trials need authenticated Rhodiola rosea, standardized marker compounds, adequate sex representation, preregistered outcomes, and protocols relevant to specific sports.",
        "research_geo": None,
        "image": (
            156924638,
            "Квіти золотого кореня (Rhodiola rosea).jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/%D0%9A%D0%B2%D1%96%D1%82%D0%B8_%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B3%D0%BE_%D0%BA%D0%BE%D1%80%D0%B5%D0%BD%D1%8F_%28Rhodiola_rosea%29.jpg/1280px-%D0%9A%D0%B2%D1%96%D1%82%D0%B8_%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B3%D0%BE_%28Rhodiola_rosea%29.jpg",
            "Maryana Twardovska",
            "CC BY 4.0",
            "https://creativecommons.org/licenses/by/4.0/",
            "Editorial research illustration; not a photograph of the reported study.",
        ),
    },
    {
        "key": "roselle",
        "common": "Roselle",
        "scientific": "Sabdariffa gossypiifolia (Mill.) M.M.Hanes & R.L.Barrett",
        "cited": "Hibiscus sabdariffa L.",
        "family": "Malvaceae",
        "powo": "77361038-1",
        "range": "Native from western tropical Africa to Sudan and introduced widely in tropical regions",
        "codes": ["CF", "TD", "CG", "CD", "GA", "GH", "NG", "SD"],
        "pmid": "38878905",
        "doi": "10.1016/j.ctim.2024.103063",
        "date": "2024-06-13",
        "title": "Clinical effects of Hibiscus sabdariffa Linn. on obesity treatment: A systematic review and meta-analysis of randomized controlled trials.",
        "authors": [
            "Piyameth Dilokthornsakul",
            "Natnicha Rattanachaisit",
            "Phiyanuch Thimkorn",
            "Supawan Pongpattanawut",
            "Witoo Dilokthornsakul",
            "Teerapon Dhippayom",
        ],
        "journal": "Complementary Therapies in Medicine",
        "types": ["Journal Article", "Systematic Review", "Meta-Analysis"],
        "headline": "Roselle review finds no clinical weight-loss benefit",
        "standfirst": "A registered review of six randomized trials and 339 participants found no meaningful differences in weight, body-mass index, or waist circumference, offering a useful counterweight to weight-loss marketing.",
        "question": "Do preparations cited as Hibiscus sabdariffa improve body weight, body-mass index, waist circumference, or waist-to-hip ratio in randomized trials?",
        "context": "Roselle calyces are used in foods and drinks, while concentrated products are marketed for metabolic goals. The review tested a narrow obesity-treatment claim rather than assuming culinary or traditional use predicts weight loss.",
        "methods": "The authors searched PubMed, EMBASE, and CENTRAL through February 2024 under a registered protocol and pooled randomized trials with random-effects models.",
        "base": "Six trials with 339 participants were included. Four tested extract capsules against placebo; two tested roselle tea against black or green tea.",
        "intervention": "Capsulated extracts or roselle tea used in the included trials.",
        "comparator": "Placebo capsules, black tea, or green tea depending on the trial.",
        "findings": [
            "The pooled weight difference was close to zero and its confidence interval crossed no effect.",
            "BMI and waist-circumference estimates were also near zero.",
            "The authors concluded that the evidence did not show a clinical obesity-treatment benefit.",
        ],
        "strength": "moderate",
        "strength_text": "A registered systematic review and consistent near-null estimates support the negative conclusion, though only six small trials and differing preparations limit precision.",
        "matters": "Well-conducted negative evidence is newsworthy because it can prevent a colorful beverage or capsule from being promoted beyond what controlled trials show.",
        "limits": [
            "Only six trials and 339 participants were available.",
            "Capsules and teas were not the same intervention.",
            "Two tea studies used active beverage comparators.",
            "Longer standardized trials remain limited.",
        ],
        "safety": "The review reports no safety concerns in included studies, but small trials and short follow-up cannot exclude uncommon effects or interactions. No efficacy finding should be read as universal product safety.",
        "unknown": [
            "The analysis does not prove roselle has no biological effects of any kind.",
            "It does not test every preparation or population.",
            "It does not support using roselle as an obesity treatment.",
        ],
        "practical": "For weight loss, the best current reading of these trials is no demonstrated clinical benefit. Food use and other research questions remain separate.",
        "traditional": "The study used the long-established name Hibiscus sabdariffa. Kew's 2025 backbone now treats that name as a synonym of Sabdariffa gossypiifolia; both names are preserved to keep research and current taxonomy traceable.",
        "preparation": "Four studies used extract capsules and two used tea. Their composition and comparators differ, so the review cannot define one uniform roselle intervention.",
        "outcomes": "The prespecified outcomes were anthropometric measures, not long-term health events. Their pooled estimates were small and compatible with no effect.",
        "related": "Further studies would need standardized products, adequate duration, preregistration, and transparent safety data, but the current evidence does not justify stronger marketing claims.",
        "research_geo": None,
        "image": (
            36622514,
            "Hibiscus. Fresh and dried.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/0/0b/Hibiscus._Fresh_and_dried.jpg",
            "T.K. Naliaka",
            "CC BY-SA 4.0",
            "https://creativecommons.org/licenses/by-sa/4.0/",
            "Documentary image of fresh and dried roselle calyces; not from the reported study.",
        ),
    },
    {
        "key": "guduchi",
        "common": "Guduchi",
        "scientific": "Tinospora cordifolia (Willd.) Hook.f. & Thomson",
        "family": "Menispermaceae",
        "powo": "907828-1",
        "range": "Native from the Indian subcontinent to Indochina",
        "codes": ["BD", "IN", "LK", "MM", "MV", "VN"],
        "pmid": "38784353",
        "doi": "10.7759/cureus.58807",
        "date": "2024-04-23",
        "title": "Safety and Efficacy of the Ayurvedic Formulation Guduchi Ghana Vati as a Preventive Remedy in COVID-19.",
        "authors": [
            "Sanjeev Sharma",
            "Pawankumar Godatwar",
            "Manohar Pareek",
            "Hml Meena",
            "Anand Sharma",
            "Sanjay Tamoli",
        ],
        "journal": "Cureus",
        "types": ["Journal Article"],
        "headline": "Large guduchi study leaves its primary prevention signal unresolved",
        "standfirst": "A community study with 10,022 completers reported no statistically significant difference in COVID-19 incidence, despite secondary severity and non-COVID illness findings; its open-label, no-intervention comparison limits causal interpretation.",
        "question": "Did Guduchi Ghana Vati change infection incidence, severity, hospitalization, or adverse reactions over 45 days in healthy community participants?",
        "context": "Guduchi is important in Ayurveda. During a pandemic, that history created interest but also heightened the need to separate prevention claims from controlled primary-outcome evidence.",
        "methods": "The multicenter, randomized, comparative community study was open label. Participants in five Rajasthan districts received the formulation for 45 days or no intervention.",
        "base": "The analysis reports 10,022 completers, making it large, but the abstract does not provide allocation counts, attrition from randomization, laboratory confirmation detail, or blinded outcome assessment.",
        "intervention": "Guduchi Ghana Vati for 45 days.",
        "comparator": "No intervention rather than placebo.",
        "findings": [
            "COVID-19 incidence was lower numerically but not statistically significant.",
            "Reported severity and non-COVID illness measures favored the intervention group.",
            "No major adverse drug reactions were observed during the study.",
        ],
        "strength": "limited",
        "strength_text": "The large sample and multicenter design are notable, but open-label exposure, no placebo, unclear attrition and outcome ascertainment, multiple secondary findings, and a nonsignificant incidence endpoint greatly limit causal confidence.",
        "matters": "The central prevention result was not statistically significant. Keeping that fact ahead of favorable secondary outcomes is essential when a traditional product is discussed in an infectious-disease context.",
        "limits": [
            "The trial was open label with a no-intervention control.",
            "The primary incidence difference was not statistically significant.",
            "The abstract does not fully report attrition or diagnostic ascertainment.",
            "Secondary infection and severity findings are vulnerable to reporting and behavior differences.",
        ],
        "safety": "No major reactions were observed in this study, but that does not settle broader safety. Published literature has separately raised liver-injury concerns around Tinospora products, species substitution, and causality; clinical safety review remains important.",
        "unknown": [
            "The study does not prove that guduchi prevents COVID-19.",
            "It does not establish an alternative to vaccination or evidence-based infection care.",
            "It does not establish safety across species, products, liver conditions, or longer use.",
        ],
        "practical": "The large participant count should not overshadow design limitations or the nonsignificant incidence result. The article supports further rigorous study, not a prevention recommendation.",
        "traditional": "Kew accepts Tinospora cordifolia as a liana native from the Indian subcontinent to Indochina. Ayurvedic use is historical context and remains distinct from proof of infection prevention.",
        "preparation": "The tested intervention was Guduchi Ghana Vati, a specific Ayurvedic formulation. Results cannot be assigned automatically to raw stems, other extracts, or products with uncertain species identity.",
        "outcomes": "The study examined infection incidence, severity, hospitalization, non-COVID illness, and adverse reactions. The incidence result—the most direct prevention question—was not significant.",
        "related": "Future work needs placebo control, masking where possible, transparent flow counts, objective case ascertainment, preregistered outcomes, and detailed liver-safety monitoring.",
        "research_geo": (
            "Rajasthan, India",
            "IN",
            "study_site",
            "Where the study was conducted",
            "The abstract explicitly reports community recruitment in five districts of Rajasthan.",
        ),
        "image": (
            115434978,
            "CS of Tinospora cordifolia root 01.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/CS_of_Tinospora_cordifolia_root_01.jpg/1280px-CS_of_Tinospora_cordifolia_root_01.jpg",
            "Adarshjchandran",
            "CC BY-SA 4.0",
            "https://creativecommons.org/licenses/by-sa/4.0/",
            "Editorial research illustration; not a photograph of the reported study.",
        ),
    },
    {
        "key": "psyllium",
        "common": "Psyllium",
        "scientific": "Plantago ovata Forssk.",
        "family": "Plantaginaceae",
        "powo": "685486-1",
        "range": "Native from southeastern Spain and North Africa to India and Somalia, and in the southwestern United States to northern Mexico",
        "codes": [
            "ES",
            "DZ",
            "MA",
            "TN",
            "LY",
            "EG",
            "CY",
            "IQ",
            "IR",
            "KW",
            "SA",
            "OM",
            "YE",
            "SO",
            "PK",
            "IN",
            "AF",
            "US",
            "MX",
        ],
        "pmid": "39479650",
        "doi": "10.1002/fsn3.3863",
        "date": "2024-08-29",
        "title": "The effect of psyllium consumption on blood pressure: Systematic review and dose-response meta-analysis of randomized controlled trials.",
        "authors": ["Zeinab Gholami", "Zamzam Paknahad"],
        "journal": "Food Science & Nutrition",
        "types": ["Journal Article", "Review"],
        "headline": "Psyllium review reports a small systolic—but not diastolic—blood-pressure change",
        "standfirst": "Across 14 randomized trials and 802 adults, psyllium was associated with a modest pooled reduction in systolic pressure while diastolic pressure did not significantly change; methods reported in the abstract leave important robustness questions.",
        "question": "What do randomized adult trials show about psyllium consumption and systolic or diastolic blood pressure?",
        "context": "Psyllium seed husk is a concentrated soluble-fiber preparation. Blood-pressure research is distinct from its better-known digestive use and should not be generalized across all Plantago products.",
        "methods": "The authors searched Scopus, Web of Science, and PubMed during a stated 2022 search period and pooled 14 randomized trials with a fixed-effects model, also examining dose and duration relationships.",
        "base": "Fourteen randomized studies with 802 adult participants contributed. The indexed abstract does not summarize diagnoses, trial quality, preparation consistency, or between-study heterogeneity.",
        "intervention": "Psyllium consumption in the included randomized trials.",
        "comparator": "Control conditions used by those trials.",
        "findings": [
            "Systolic blood pressure was lower by a pooled 2.24 mmHg.",
            "Diastolic blood pressure showed no significant difference.",
            "Dose and duration relationships were reported, but the abstract does not provide enough detail to judge their robustness.",
        ],
        "strength": "mixed",
        "strength_text": "Randomized trials and a quantitative synthesis are strengths. A fixed-effects model, sparse bias reporting, and missing heterogeneity and population detail in the abstract limit confidence in transportability.",
        "matters": "Separating systolic from diastolic results prevents a small biomarker change from becoming a broad claim that psyllium treats hypertension.",
        "limits": [
            "The abstract does not report risk-of-bias findings.",
            "A fixed-effects model assumes one common underlying effect.",
            "Population and preparation differences are not summarized.",
            "The clinical importance of a small average systolic change varies by context.",
        ],
        "safety": "Psyllium expands with liquid and can affect medicine absorption; the indexed efficacy abstract does not provide a safety synthesis. Appropriate product instructions and individual clinical context remain important.",
        "unknown": [
            "The review does not prove prevention of cardiovascular events.",
            "It does not establish psyllium as a replacement for hypertension treatment.",
            "It does not show a diastolic-pressure benefit.",
        ],
        "practical": "The result is a modest systolic signal with no corresponding diastolic change. It belongs in a broader evidence discussion, not as standalone treatment advice.",
        "traditional": "Kew accepts Plantago ovata across dry regions spanning several continents and records medicinal seed use. The research concerns processed psyllium fiber, not every species or plant part in the genus.",
        "preparation": "Psyllium generally refers to husk-derived soluble fiber, but included products and administration protocols may differ. The abstract does not support one universal regimen.",
        "outcomes": "Systolic and diastolic pressure were analyzed separately. Only the systolic pooled estimate changed significantly, and neither measure is itself a patient-important clinical event.",
        "related": "Future syntheses should report bias, heterogeneity, baseline pressure, verified fiber composition, adverse events, and absolute adherence data.",
        "safety_source": {
            "source_id": "ema-herbal:plantaginis-ovatae-seminis-tegumentum",
            "provider": "ema-herbal",
            "support_role": "safety",
            "external_identifier": "EMA/HMPC/313600/2013",
            "pmid": None,
            "doi": None,
            "canonical_url": "https://www.ema.europa.eu/en/medicines/herbal/plantaginis-ovatae-seminis-tegumentum",
            "title": "Plantaginis ovatae seminis tegumentum - herbal medicinal product",
            "authors": ["Committee on Herbal Medicinal Products"],
            "journal": "European Medicines Agency",
            "publication_date": "2013-07-23",
            "publication_types": ["European Union herbal monograph"],
            "retraction_status": "not_applicable",
        },
        "research_geo": None,
        "image": (
            47259296,
            "2016-02-04 Flohsamenschalen (Plantago ovata) Psyllium Seed Husks anagoria.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/2016-02-04_Flohsamenschalen_%28Plantago_ovata%29_Psyllium_Seed_Husks_anagoria.jpg/1280px-2016-02-04_Flohsamenschalen_%28Plantago_ovata%29_Psyllium_Seed_Husks_anagoria.jpg",
            "Anagoria",
            "CC BY 3.0",
            "https://creativecommons.org/licenses/by/3.0/",
            "Documentary image of psyllium seed husks; not from the reported study.",
        ),
    },
    {
        "key": "andrographis",
        "common": "Andrographis",
        "scientific": "Andrographis paniculata (Burm.f.) Wall. ex Nees",
        "family": "Acanthaceae",
        "powo": "45226-1",
        "range": "Native to the Indian subcontinent and introduced across parts of tropical Asia and the Americas",
        "codes": ["BD", "IN", "NP", "LK"],
        "pmid": "37821383",
        "doi": "10.5582/ddt.2023.01053",
        "date": "2023-10-11",
        "title": "Efficacy of Andrographis paniculata spray in acute pharyngitis: A randomized controlled trial.",
        "authors": ["Risa Okonogi", "Vich Thampanya", "Siriporn Okonogi"],
        "journal": "Drug Discoveries & Therapeutics",
        "types": ["Randomized Controlled Trial", "Journal Article"],
        "headline": "Andrographis throat-spray trial needs a true placebo comparison",
        "standfirst": "A double-blind study in 60 adults with self-limited viral pharyngitis found symptoms improved with both andrographis and chamomile sprays, with a borderline difference in response duration and no placebo-only group.",
        "question": "Does a local Andrographis paniculata spray change symptom response compared with a chamomile spray in acute viral pharyngitis?",
        "context": "Andrographis is used in several traditional systems and respiratory products. Because viral sore throat commonly improves on its own, comparator choice is central to interpreting symptom change.",
        "methods": "Sixty adults were randomized under double blinding to andrographis or an active chamomile spray. Participants scored symptoms and clinicians scored throat redness and swelling.",
        "base": "The trial included 60 adults with acute viral pharyngitis. The abstract does not state group sizes, diagnostic confirmation, attrition, or a prespecified primary outcome.",
        "intervention": "A locally applied Andrographis paniculata spray.",
        "comparator": "A chamomile spray, which is an active botanical comparator rather than an inert placebo.",
        "findings": [
            "Signs and symptoms improved significantly within both groups.",
            "Reported response duration averaged 1.9 versus 2.5 days, with p=0.049.",
            "No adverse events were noted in either small group.",
        ],
        "strength": "limited",
        "strength_text": "Randomization and blinding help, but the active comparator, no untreated or inert-placebo group, small sample, self-limiting illness, multiple endpoints, and borderline p-value restrict causal interpretation.",
        "matters": "The study illustrates why within-group improvement is not enough: spontaneous recovery and an active comparator make it difficult to determine absolute benefit.",
        "limits": [
            "There was no inert placebo or usual-care-only arm.",
            "Acute viral pharyngitis commonly improves spontaneously.",
            "Only 60 adults participated.",
            "The response-duration result was borderline and multiple symptoms were measured.",
        ],
        "safety": "No events were observed in 60 participants, which cannot exclude uncommon reactions. A local spray also does not establish the safety of systemic andrographis products.",
        "unknown": [
            "The trial does not prove benefit over inert placebo or natural recovery.",
            "It does not establish treatment of bacterial throat infection.",
            "It does not support extrapolation to oral or systemic products.",
        ],
        "practical": "The trial offers a comparator-specific signal, but an inert-placebo design is needed before attributing symptom recovery confidently to andrographis.",
        "traditional": "Kew accepts Andrographis paniculata as native to the Indian subcontinent. Traditional respiratory use helps frame the question but cannot resolve placebo effects or spontaneous recovery.",
        "preparation": "The exposure was a local throat spray. Its formulation and route differ fundamentally from tablets, decoctions, and whole-herb preparations.",
        "outcomes": "Patient-rated sore throat, swallowing difficulty, cough, and clinician-rated mucosal signs were tracked. Improvement in both groups complicates attribution.",
        "related": "A stronger replication would use an inert matched spray, define one primary endpoint, document virologic criteria, and report allocation, attrition, and adverse events fully.",
        "research_geo": (
            "Thailand",
            "TH",
            "research_institution",
            "Research institution affiliation",
            "PubMed affiliations identify hospitals and a university in Chiang Rai and Chiang Mai; the abstract does not explicitly state the participant site.",
        ),
        "image": (
            17710458,
            "Andrographis paniculata Plant.JPG",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Andrographis_paniculata_Plant.JPG/1280px-Andrographis_paniculata_Plant.JPG",
            "Viswaprabha",
            "CC BY-SA 3.0",
            "https://creativecommons.org/licenses/by-sa/3.0/",
            "Botanical reference image; not an image from the reported study.",
        ),
    },
    {
        "key": "gymnema",
        "common": "Gymnema",
        "scientific": "Gymnema sylvestre (Retz.) R.Br. ex Sm.",
        "family": "Apocynaceae",
        "powo": "60454719-2",
        "range": "Native across tropical and subtropical Africa and Asia to Australia",
        "codes": [
            "IN",
            "LK",
            "BD",
            "MM",
            "TH",
            "VN",
            "CN",
            "SA",
            "YE",
            "ET",
            "KE",
            "TZ",
            "ZA",
            "MG",
            "AU",
        ],
        "pmid": "39064727",
        "doi": "10.3390/nu16142284",
        "date": "2024-07-16",
        "title": "Comparative Effects of Gymnema sylvestre and Berberine on Adipokines, Body Composition, and Metabolic Parameters in Obese Patients: A Randomized Study.",
        "authors": [
            "Cindy Bandala",
            "Jazmín Carro-Rodríguez",
            "Noemí Cárdenas-Rodríguez",
            "Itzel Peña-Montero",
            "Modesto Gómez-López",
            "Ana Paola Hernández-Roldán",
            "Juan Carlos Huerta-Cruz",
            "Felipe Muñoz-González",
            "Iván Ignacio-Mejía",
            "Brayan Domínguez",
            "Eleazar Lara-Padilla",
        ],
        "journal": "Nutrients",
        "types": [
            "Journal Article",
            "Randomized Controlled Trial",
            "Comparative Study",
        ],
        "headline": "Gymnema comparison separates glucose signals from body-composition claims",
        "standfirst": "In 50 Mexican adults with obesity, three months of Gymnema sylvestre was associated with fasting-glucose and resistin-expression changes, while the berberine arm—not gymnema—showed the stronger body-composition and blood-pressure pattern.",
        "question": "How do Gymnema sylvestre and berberine compare on metabolic measures, body composition, blood pressure, adipokine gene expression, and safety over three months?",
        "context": "Gymnema has a traditional association with sweet taste and glucose-related use. This head-to-head study did not include an inert placebo, so it compares two products rather than estimating either one's absolute effect.",
        "methods": "Fifty adults with obesity were randomized to gymnema or berberine for three months. Baseline and final biochemical, body-composition, blood-pressure, adipokine-expression, and safety measures were compared.",
        "base": "Fifty Mexican adult participants were split between two active treatments. The abstract does not report blinding, placebo control, attrition, or detailed baseline balance.",
        "intervention": "A Gymnema sylvestre preparation for three months.",
        "comparator": "Berberine, another active natural product; there was no inert placebo group.",
        "findings": [
            "The gymnema arm showed lower fasting glucose and resistin expression after treatment.",
            "The berberine arm showed broader body-composition, blood-pressure, and selected adipokine changes.",
            "Gastrointestinal symptoms were the most frequent adverse effects in both groups and eased during the first month.",
        ],
        "strength": "limited",
        "strength_text": "Random allocation and direct active comparison are useful, but 50 participants, no placebo, short follow-up, many outcomes, and uncertain blinding prevent firm gymnema efficacy conclusions.",
        "matters": "The result challenges a generalized metabolic claim: gymnema's reported pattern was narrower than berberine's, and without placebo neither arm reveals the absolute treatment effect.",
        "limits": [
            "Only 50 adults participated.",
            "There was no placebo or untreated control.",
            "Many biochemical and gene-expression outcomes were assessed.",
            "The abstract does not report allocation concealment, blinding, or attrition.",
        ],
        "safety": "Gastrointestinal symptoms occurred in both groups and reportedly attenuated. Three months in a small sample cannot establish uncommon, long-term, interaction, pregnancy, or diabetes-medication safety.",
        "unknown": [
            "The study does not prove gymnema causes weight loss.",
            "It does not establish superiority to standard obesity or diabetes care.",
            "Gene-expression changes do not themselves prove improved clinical outcomes.",
        ],
        "practical": "The gymnema arm produced a narrow exploratory metabolic signal. A placebo-controlled, adequately powered trial is needed before stronger conclusions.",
        "traditional": "Kew accepts Gymnema sylvestre across the tropical and subtropical Old World to Australia. Traditional glucose-related use provides context but does not resolve the trial's missing placebo comparison.",
        "preparation": "The trial used a gymnema product under a three-month protocol. Product standardization and composition must be known before comparing it with other extracts or leaf preparations.",
        "outcomes": "Fasting glucose, body composition, blood pressure, safety measures, and several adipokine genes were measured. Biomarker and expression changes are not equivalent to fewer complications.",
        "related": "Future research should add placebo, preregister one primary endpoint, report participant flow and product chemistry, and account for concurrent diet, medicines, and activity.",
        "research_geo": (
            "Mexico",
            "MX",
            "participant_location",
            "Participant location",
            "The indexed abstract explicitly describes the participants as Mexican adults.",
        ),
        "image": (
            197247322,
            "Gymnema sylvestre-1-Semmozhi Poonga-coimbatore-India.jpg",
            "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Gymnema_sylvestre-1-Semmozhi_Poonga-coimbatore-India.jpg/1280px-Gymnema_sylvestre-1-Semmozhi_Poonga-coimbatore-India.jpg",
            "Yercaud-elango",
            "CC BY 4.0",
            "https://creativecommons.org/licenses/by/4.0/",
            "Botanical reference image; not an image from the reported study.",
        ),
    },
]

ARTICLE_TYPES = {
    "moringa": "Meta-Analysis",
    "holy-basil": "Randomized Controlled Trial",
    "centella": "Randomized Controlled Trial",
    "black-seed": "Meta-Analysis",
    "saffron": "Meta-Analysis",
    "bacopa": "Randomized Controlled Trial",
    "rhodiola": "Systematic Review",
    "roselle": "Meta-Analysis",
    "guduchi": "Randomized Controlled Trial",
    "psyllium": "Systematic Review",
    "andrographis": "Randomized Controlled Trial",
    "gymnema": "Randomized Controlled Trial",
}


def _source(record: dict) -> dict:
    return {
        "source_id": f"pubmed:{record['pmid']}",
        "provider": "pubmed-eutils",
        "support_role": "primary_evidence",
        "pmid": record["pmid"],
        "doi": record["doi"],
        "canonical_url": f"https://pubmed.ncbi.nlm.nih.gov/{record['pmid']}/",
        "title": record["title"],
        "authors": record["authors"],
        "journal": record["journal"],
        "publication_date": record["date"],
        "publication_types": record["types"],
        "retraction_status": "checked_clear",
    }


def _powo_source(record: dict) -> dict:
    return {
        "source_id": f"powo:{record['powo']}",
        "provider": "kew-powo",
        "support_role": "taxonomy_distribution",
        "external_identifier": record["powo"],
        "pmid": None,
        "doi": None,
        "canonical_url": f"https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:{record['powo']}",
        "title": f"{record['scientific']} — Plants of the World Online",
        "authors": ["Royal Botanic Gardens, Kew"],
        "journal": "Plants of the World Online",
        "publication_date": None,
        "publication_types": ["Taxonomic backbone", "Structured distribution"],
        "retraction_status": "not_applicable",
    }


def _trace(source_id: str, location: str) -> dict:
    return {"source_ids": [source_id], "evidence_locations": [location]}


def _media(record: dict) -> dict:
    page_id, file_name, url, creator, license_name, license_url, caption = record[
        "image"
    ]
    parsed = urllib.parse.urlsplit(url)
    if "/commons/thumb/" in parsed.path:
        original_path = parsed.path.replace("/commons/thumb/", "/commons/").rsplit(
            "/", 1
        )[0]
        url = urllib.parse.urlunsplit(
            ("https", "upload.wikimedia.org", original_path, "", "")
        )
    extension = ".png" if file_name.lower().endswith(".png") else ".jpg"
    local_name = f"m4c-{record['key']}{extension}"
    local_file = MEDIA_DIR / local_name
    redirect_name = urllib.parse.quote(file_name.replace(" ", "_"))
    download_url = (
        f"https://commons.wikimedia.org/wiki/Special:Redirect/file/{redirect_name}"
        "?width=1200"
    )
    temporary_file = local_file.with_suffix(local_file.suffix + ".download")
    if not local_file.exists():
        # Commons rate-limits bursty image retrieval. Resume completed files and
        # space the remaining requests rather than downloading the batch again.
        time.sleep(5)
        subprocess.run(
            [
                "curl.exe",
                "-L",
                "--fail",
                "--silent",
                "--show-error",
                "--retry",
                "3",
                "--retry-delay",
                "10",
                "--retry-all-errors",
                download_url,
                "--output",
                str(temporary_file),
            ],
            check=True,
            timeout=120,
        )
        os.replace(temporary_file, local_file)
    payload = local_file.read_bytes()
    if len(payload) < 10_000:
        raise RuntimeError(f"downloaded media is unexpectedly small: {file_name}")
    checksum = hashlib.sha256(payload).hexdigest()
    classification = (
        "editorial_illustration"
        if caption.startswith("Editorial research illustration")
        else "botanical_reference"
        if caption.startswith("Botanical reference image")
        else "documentary"
    )
    return {
        "local_path": f"/media/discoveries/{local_name}",
        "source_page": f"https://commons.wikimedia.org/?curid={page_id}",
        "direct_asset_url": url,
        "stable_media_identifier": f"commons:{page_id}",
        "creator": creator,
        "license": license_name,
        "license_url": license_url,
        "attribution": f"{file_name} — {creator}, {license_name}, via Wikimedia Commons",
        "checksum_sha256": checksum,
        "plant_relevance": f"The source description identifies {record['scientific']} or its studied preparation.",
        "classification": classification,
        "caption": caption,
        "alt_text": f"{record['common']} editorial discovery image",
    }


def _article(record: dict) -> dict:
    primary_id = f"pubmed:{record['pmid']}"
    powo_id = f"powo:{record['powo']}"
    geography = [
        {
            "country_or_region": record["range"],
            "iso_country_code": None,
            "iso_country_codes": record["codes"],
            "geography_kind": "botanical_distribution",
            "evidence_type": "native_distribution",
            "source_id": powo_id,
            "supporting_text_location": "POWO: Distribution / Native to",
            "confidence": "high",
            "qualification": "Highlighted countries represent the documented native range summarized by Kew; consult the source for subnational botanical regions.",
            "display_label": record["range"],
            "map_title": "Documented botanical distribution",
        }
    ]
    if record["research_geo"]:
        label, code, evidence_type, title, qualification = record["research_geo"]
        geography.append(
            {
                "country_or_region": label,
                "iso_country_code": code,
                "iso_country_codes": [],
                "geography_kind": "research_geography",
                "evidence_type": evidence_type,
                "source_id": primary_id,
                "supporting_text_location": "PubMed indexed abstract or affiliations",
                "confidence": "qualified" if "affiliation" in evidence_type else "high",
                "qualification": qualification,
                "display_label": label,
                "map_title": title,
            }
        )
    core_locations = {
        "overview": "Article title and abstract",
        "research_question": "Abstract: objective or background",
        "why_studied": "Abstract: background",
        "methods": "Abstract: methods",
        "evidence_base": "Abstract: methods",
        "findings": "Abstract: results",
        "why_matters": "Abstract: results and conclusion",
        "evidence_strength": "Publication types and abstract: methods",
        "limitations": "Abstract: design and reported methods",
        "safety": "Abstract: adverse-event reporting or absence of safety detail",
        "cannot_conclude": "Abstract: design boundaries and conclusion",
    }
    additional = [
        (
            "traditional_context",
            "Traditional-medicine context",
            record["traditional"],
            powo_id,
            "POWO: Uses and general information",
        ),
        (
            "botanical_identity",
            "Botanical identity",
            f"Kew accepts {record['scientific']} in {record['family']}. "
            + (
                f"The study cited it as {record['cited']}. "
                if record.get("cited")
                else ""
            )
            + "The taxonomic authority is recorded independently from the clinical paper so a common name cannot silently establish identity.",
            powo_id,
            "POWO: accepted name and classification",
        ),
        (
            "preparation",
            "Preparation or plant part studied",
            record["preparation"],
            primary_id,
            "Abstract: intervention description",
        ),
        (
            "outcomes",
            "Outcomes measured",
            record["outcomes"],
            primary_id,
            "Abstract: methods and results",
        ),
        (
            "related_research",
            "What should researchers examine next?",
            record["related"],
            primary_id,
            "Abstract: design limitations and conclusion",
        ),
        (
            "botanical_distribution",
            "Botanical distribution",
            f"Kew records this taxon as {record['range'].lower()}. Botanical occurrence describes the plant's documented range; it does not identify where the reported study took place.",
            powo_id,
            "POWO: Distribution",
        ),
    ]
    sources = [_source(record), _powo_source(record)]
    if record.get("safety_source"):
        sources.append(record["safety_source"])
    section_sources = {
        key: _trace(primary_id, location) for key, location in core_locations.items()
    }
    if record.get("safety_source"):
        section_sources["safety"] = {
            "source_ids": [primary_id, record["safety_source"]["source_id"]],
            "evidence_locations": [
                core_locations["safety"],
                "EMA: risks, interactions, and safe-use conditions",
            ],
        }
    payload = {
        "slug": f"{record['key']}-{record['pmid']}-evidence-report",
        "content_version": 1,
        "content_checksum": "0" * 64,
        "plant_slug": None,
        "common_name": record["common"],
        "scientific_name": record["scientific"],
        "botanical_identity": {
            "common_name": record["common"],
            "accepted_scientific_name": record["scientific"],
            "cited_scientific_name": record.get("cited"),
            "family": record["family"],
            "authority_source_id": powo_id,
            "authority_taxon_id": record["powo"],
            "authority_url": f"https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:{record['powo']}",
            "accepted": True,
        },
        "headline": record["headline"],
        "standfirst": record["standfirst"],
        "publication_date": record["date"],
        "research_date": None,
        "article_type": ARTICLE_TYPES[record["key"]],
        "research_question": record["question"],
        "research_context": record["context"],
        "study_design": record["methods"],
        "evidence_base": record["base"],
        "intervention": record["intervention"],
        "comparator": record["comparator"],
        "main_findings": record["findings"],
        "evidence_strength": record["strength"],
        "evidence_strength_rationale": record["strength_text"],
        "why_matters": record["matters"],
        "limitations": record["limits"],
        "safety_context": record["safety"],
        "cannot_conclude": record["unknown"],
        "practical_interpretation": record["practical"],
        "section_sources": section_sources,
        "additional_sections": [
            {
                "key": key,
                "heading": heading,
                "text": text,
                "source_ids": [source_id],
                "evidence_locations": [location],
            }
            for key, heading, text, source_id, location in additional
        ],
        "geography": geography,
        "image_caption": None,
        "hero_image": _media(record),
        "sources": sources,
    }
    article = CuratedDiscovery.model_validate(payload)
    article.content_checksum = article.calculated_checksum()
    return article.model_dump(mode="json")


def main() -> None:
    MEDIA_DIR.mkdir(parents=True, exist_ok=True)
    articles = [_article(record) for record in RECORDS]
    selected = [
        {
            "candidate_plant": record["scientific"],
            "candidate_pmid": record["pmid"],
            "candidate_doi": record["doi"],
            "decision": "selected",
            "study_type": record["types"],
            "source_completeness": "PubMed metadata and abstract plus Kew taxonomy and distribution verified",
        }
        for record in RECORDS
    ]
    rejected = [
        {
            "candidate_plant": "Azadirachta indica A.Juss.",
            "candidate_pmid": None,
            "candidate_doi": None,
            "decision": "rejected",
            "study_type": None,
            "source_completeness": "No recent sufficiently informative plant-specific human source selected.",
        },
        {
            "candidate_plant": "Berberis vulgaris L.",
            "candidate_pmid": "39413550",
            "candidate_doi": "10.1016/j.jaim.2024.101039",
            "decision": "rejected",
            "study_type": ["Systematic Review", "Meta-Analysis"],
            "source_completeness": "The pooled intervention combined Berberis vulgaris with B. integerrima, preventing a clean species-specific article.",
        },
        {
            "candidate_plant": "Urtica dioica L.",
            "candidate_pmid": "38716323",
            "candidate_doi": None,
            "decision": "rejected",
            "study_type": ["Randomized Controlled Trial"],
            "source_completeness": "The tested five-herb mixture could not support a nettle-specific finding.",
        },
    ]
    payload = {
        "schema_version": 2,
        "batch_id": "milestone-4c-new-plants",
        "selection_audit": selected + rejected,
        "articles": articles,
    }
    CORPUS_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps({"articles": len(articles), "media": len(articles)}))


if __name__ == "__main__":
    main()
